/**
 * demo.js — Perfiles de ejemplo para probar el sistema sin gastar un peso de API.
 * Están armados para cubrir las tres situaciones que se ven en la calle:
 * el perfil abandonado, el perfil a medio hacer y el perfil bien trabajado.
 */

const hace = (d) => new Date(Date.now() - d * 86400000).toISOString();

export const PERFILES_DEMO = {
  panaderia: {
    fuente: 'demo',
    placeId: 'demo_panaderia_01',
    nombre: 'Panadería La Esquina de Oro',
    direccion: 'Av. Rivadavia 8420, Buenos Aires',
    telefono: '+54 11 4635-2211',
    sitioWeb: null,
    mapsUrl: 'https://maps.google.com/?cid=demo1',
    estado: 'OPERATIONAL',
    categoriaPrimaria: 'bakery',
    categoriaPrimariaLabel: 'Panadería',
    categoriasSecundarias: [],
    descripcion: '',
    rating: 4.1,
    cantidadResenas: 27,
    tasaRespuestaResenas: 0,
    diasDesdeUltimaResena: 74,
    cantidadFotos: 4,
    horarios: [{ dia: 1 }, { dia: 2 }, { dia: 3 }, { dia: 4 }, { dia: 5 }],
    horariosEspeciales: [],
    atributos: ['takeout'],
    servicios: [],
    postsUltimos30Dias: 0,
    ofertasActivas: 0,
    mensajeriaActiva: false,
    reservasActivas: false,
    diasDesdeUltimaFoto: 420,
    tiposDeFoto: { fachada: true, interior: false, producto: true, equipo: false },
    redes: {},
    web: null,
    resenasMuestra: [
      { autor: 'Marta G.', rating: 5, texto: 'Las facturas son las mejores del barrio.', fecha: hace(74), tieneRespuesta: false },
      { autor: 'Juan P.', rating: 2, texto: 'Fui un domingo y estaba cerrado, decía abierto en Google.', fecha: hace(96), tieneRespuesta: false },
    ],
  },

  estudio: {
    fuente: 'demo',
    placeId: 'demo_estudio_02',
    nombre: 'Estudio Contable Ferrari & Asociados',
    direccion: 'San Martín 1150, Piso 4, Rosario, Santa Fe',
    telefono: '+54 341 425-7788',
    sitioWeb: 'https://ejemplo-estudioferrari.com.ar',
    mapsUrl: 'https://maps.google.com/?cid=demo2',
    estado: 'OPERATIONAL',
    categoriaPrimaria: 'accounting',
    categoriaPrimariaLabel: 'Estudio contable',
    categoriasSecundarias: ['tax_consultant', 'financial_consultant'],
    descripcion: 'Estudio contable con más de 20 años de trayectoria.',
    rating: 4.8,
    cantidadResenas: 12,
    tasaRespuestaResenas: 0.4,
    diasDesdeUltimaResena: 31,
    cantidadFotos: 11,
    horarios: [{ dia: 1 }, { dia: 2 }, { dia: 3 }, { dia: 4 }, { dia: 5 }, { dia: 6 }, { dia: 0 }],
    horariosEspeciales: [],
    atributos: ['restroom', 'wheelchairAccessibleEntrance'],
    servicios: ['Liquidación de sueldos', 'Monotributo', 'Balances'],
    postsUltimos30Dias: 1,
    ofertasActivas: 0,
    mensajeriaActiva: false,
    reservasActivas: false,
    diasDesdeUltimaFoto: 95,
    tiposDeFoto: { fachada: true, interior: true, producto: false, equipo: true },
    redes: { linkedin: true },
    web: {
      ok: true, status: 200, https: true, viewport: true, ms: 1450, pesoKB: 220,
      schemaLocalBusiness: false, napTelefono: true, napDireccion: true,
      redes: { linkedin: true, instagram: null, facebook: null },
    },
    resenasMuestra: [],
  },

  clinica: {
    fuente: 'demo',
    placeId: 'demo_clinica_03',
    nombre: 'Clínica Dental Sonrisa Plena',
    direccion: 'Av. Colón 2233, Córdoba',
    telefono: '+54 351 489-1200',
    sitioWeb: 'https://ejemplo-sonrisaplena.com',
    mapsUrl: 'https://maps.google.com/?cid=demo3',
    estado: 'OPERATIONAL',
    categoriaPrimaria: 'dentist',
    categoriaPrimariaLabel: 'Odontólogo',
    categoriasSecundarias: ['dental_clinic', 'orthodontist', 'cosmetic_dentist'],
    descripcion: 'Clínica odontológica integral en el centro de Córdoba. Ofrecemos implantes, ortodoncia invisible, odontopediatría, estética dental y urgencias con turnos en el día. Atendemos las principales obras sociales y prepagas. Contamos con tecnología de escaneo intraoral y radiología digital de baja dosis. Estacionamiento propio y acceso para sillas de ruedas. Más de 15 años atendiendo familias del barrio Nueva Córdoba y alrededores, con un equipo de 8 profesionales especializados.',
    rating: 4.7,
    cantidadResenas: 186,
    tasaRespuestaResenas: 0.82,
    diasDesdeUltimaResena: 4,
    cantidadFotos: 58,
    horarios: [{ dia: 1 }, { dia: 2 }, { dia: 3 }, { dia: 4 }, { dia: 5 }, { dia: 6 }, { dia: 0 }],
    horariosEspeciales: [{ fecha: '2026-12-25' }, { fecha: '2027-01-01' }],
    atributos: ['restroom', 'wheelchairAccessibleEntrance', 'wheelchairAccessibleParking', 'acceptsCreditCards', 'acceptsDebitCards', 'freeParkingLot', 'goodForChildren', 'appointmentRequired'],
    servicios: ['Implantes', 'Ortodoncia invisible', 'Blanqueamiento', 'Odontopediatría', 'Endodoncia', 'Periodoncia', 'Urgencias', 'Prótesis', 'Estética dental', 'Limpieza'],
    postsUltimos30Dias: 5,
    ofertasActivas: 1,
    mensajeriaActiva: true,
    reservasActivas: true,
    diasDesdeUltimaFoto: 12,
    tiposDeFoto: { fachada: true, interior: true, producto: true, equipo: true },
    redes: { instagram: true, facebook: true, whatsapp: true },
    web: {
      ok: true, status: 200, https: true, viewport: true, ms: 890, pesoKB: 140,
      schemaLocalBusiness: true, napTelefono: true, napDireccion: true,
      redes: { instagram: true, facebook: true, whatsapp: true },
    },
    resenasMuestra: [],
  },
};

/** Competidores ficticios de ejemplo para probar la comparación de perfiles en modo demo. */
export const COMPETENCIA_DEMO = ['clinica', 'estudio'];
